%
% species_parent(species_name, parent_species_name). note: parent_species_name might be 'none'.
% child pok have parent_species_name = none
species_parent(abomasnow, snover).
species_parent(abra, none).
species_parent(absol, none).
species_parent(accelgor, shelmet).
species_parent(aegislash, doublade).
species_parent(aerodactyl, none).
species_parent(aggron, lairon).
species_parent(aipom, none).
species_parent(alakazam, kadabra).
species_parent(alomomola, none).
species_parent(altaria, swablu).
species_parent(amaura, none).
species_parent(ambipom, aipom).
species_parent(amoonguss, foongus).
species_parent(ampharos, flaaffy).
species_parent(anorith, none).
species_parent(arbok, ekans).
species_parent(arcanine, growlithe).
species_parent(arceus, none).
species_parent(archen, none).
species_parent(archeops, archen).
species_parent(ariados, spinarak).
species_parent(armaldo, anorith).
species_parent(aromatisse, spritzee).
species_parent(aron, none).
species_parent(articuno, none).
species_parent(audino, none).
species_parent(aurorus, amaura).
species_parent(avalugg, bergmite).
species_parent(axew, none).
species_parent(azelf, none).
species_parent(azumarill, marill).
species_parent(azurill, none).
species_parent(bagon, none).
species_parent(baltoy, none).
species_parent(banette, shuppet).
species_parent(barbaracle, binacle).
species_parent(barboach, none).
species_parent(basculin, none).
species_parent(bastiodon, shieldon).
species_parent(bayleef, chikorita).
species_parent(beartic, cubchoo).
species_parent(beautifly, silcoon).
species_parent(beedrill, kakuna).
species_parent(beheeyem, elgyem).
species_parent(beldum, none).
species_parent(bellossom, gloom).
species_parent(bellsprout, none).
species_parent(bergmite, none).
species_parent(bibarel, bidoof).
species_parent(bidoof, none).
species_parent(binacle, none).
species_parent(bisharp, pawniard).
species_parent(blastoise, wartortle).
species_parent(blaziken, combusken).
species_parent(blissey, chansey).
species_parent(blitzle, none).
species_parent(boldore, roggenrola).
species_parent(bonsly, none).
species_parent(bouffalant, none).
species_parent(braixen, fennekin).
species_parent(braviary, rufflet).
species_parent(breloom, shroomish).
species_parent(bronzong, bronzor).
species_parent(bronzor, none).
species_parent(budew, none).
species_parent(buizel, none).
species_parent(bulbasaur, none).
species_parent(buneary, none).
species_parent(bunnelby, none).
species_parent(burmy, none).
species_parent(butterfree, metapod).
species_parent(cacnea, none).
species_parent(cacturne, cacnea).
species_parent(camerupt, numel).
species_parent(carbink, none).
species_parent(carnivine, none).
species_parent(carracosta, tirtouga).
species_parent(carvanha, none).
species_parent(cascoon, wurmple).
species_parent(castform, none).
species_parent(caterpie, none).
species_parent(celebi, none).
species_parent(chandelure, lampent).
species_parent(chansey, happiny).
species_parent(charizard, charmeleon).
species_parent(charmander, none).
species_parent(charmeleon, charmander).
species_parent(chatot, none).
species_parent(cherrim, cherubi).
species_parent(cherubi, none).
species_parent(chesnaught, quilladin).
species_parent(chespin, none).
species_parent(chikorita, none).
species_parent(chimchar, none).
species_parent(chimecho, chingling).
species_parent(chinchou, none).
species_parent(chingling, none).
species_parent(cinccino, minccino).
species_parent(clamperl, none).
species_parent(clauncher, none).
species_parent(clawitzer, clauncher).
species_parent(claydol, baltoy).
species_parent(clefable, clefairy).
species_parent(clefairy, cleffa).
species_parent(cleffa, none).
species_parent(cloyster, shellder).
species_parent(cobalion, none).
species_parent(cofagrigus, yamask).
species_parent(combee, none).
species_parent(combusken, torchic).
species_parent(conkeldurr, gurdurr).
species_parent(corphish, none).
species_parent(corsola, none).
species_parent(cottonee, none).
species_parent(cradily, lileep).
species_parent(cranidos, none).
species_parent(crawdaunt, corphish).
species_parent(cresselia, none).
species_parent(croagunk, none).
species_parent(crobat, golbat).
species_parent(croconaw, totodile).
species_parent(crustle, dwebble).
species_parent(cryogonal, none).
species_parent(cubchoo, none).
species_parent(cubone, none).
species_parent(cyndaquil, none).
species_parent(darkrai, none).
species_parent(darmanitan, darumaka).
species_parent(darumaka, none).
species_parent(dedenne, none).
species_parent(deerling, none).
species_parent(deino, none).
species_parent(delcatty, skitty).
species_parent(delibird, none).
species_parent(delphox, braixen).
species_parent(deoxys, none).
species_parent(dewgong, seel).
species_parent(dewott, oshawott).
species_parent(dialga, none).
species_parent(diancie, none).
species_parent(diggersby, bunnelby).
species_parent(diglett, none).
species_parent(ditto, none).
species_parent(dodrio, doduo).
species_parent(doduo, none).
species_parent(donphan, phanpy).
species_parent(doublade, honedge).
species_parent(dragalge, skrelp).
species_parent(dragonair, dratini).
species_parent(dragonite, dragonair).
species_parent(drapion, skorupi).
species_parent(dratini, none).
species_parent(drifblim, drifloon).
species_parent(drifloon, none).
species_parent(drilbur, none).
species_parent(drowzee, none).
species_parent(druddigon, none).
species_parent(ducklett, none).
species_parent(dugtrio, diglett).
species_parent(dunsparce, none).
species_parent(duosion, solosis).
species_parent(durant, none).
species_parent(dusclops, duskull).
species_parent(dusknoir, dusclops).
species_parent(duskull, none).
species_parent(dustox, cascoon).
species_parent(dwebble, none).
species_parent(eelektrik, tynamo).
species_parent(eelektross, eelektrik).
species_parent(eevee, none).
species_parent(ekans, none).
species_parent(electabuzz, elekid).
species_parent(electivire, electabuzz).
species_parent(electrike, none).
species_parent(electrode, voltorb).
species_parent(elekid, none).
species_parent(elgyem, none).
species_parent(emboar, pignite).
species_parent(emolga, none).
species_parent(empoleon, prinplup).
species_parent(entei, none).
species_parent(escavalier, karrablast).
species_parent(espeon, eevee).
species_parent(espurr, none).
species_parent(excadrill, drilbur).
species_parent(exeggcute, none).
species_parent(exeggutor, exeggcute).
species_parent(exploud, loudred).
species_parent(farfetchd, none).
species_parent(fearow, spearow).
species_parent(feebas, none).
species_parent(fennekin, none).
species_parent(feraligatr, croconaw).
species_parent(ferroseed, none).
species_parent(ferrothorn, ferroseed).
species_parent(finneon, none).
species_parent(flaaffy, mareep).
species_parent(flabebe, none).
species_parent(flareon, eevee).
species_parent(fletchinder, fletchling).
species_parent(fletchling, none).
species_parent(floatzel, buizel).
species_parent(floette, flabebe).
species_parent(florges, floette).
species_parent(flygon, vibrava).
species_parent(foongus, none).
species_parent(forretress, pineco).
species_parent(fraxure, axew).
species_parent(frillish, none).
species_parent(froakie, none).
species_parent(frogadier, froakie).
species_parent(froslass, snorunt).
species_parent(furfrou, none).
species_parent(furret, sentret).
species_parent(gabite, gible).
species_parent(gallade, kirlia).
species_parent(galvantula, joltik).
species_parent(garbodor, trubbish).
species_parent(garchomp, gabite).
species_parent(gardevoir, kirlia).
species_parent(gastly, none).
species_parent(gastrodon, shellos).
species_parent(genesect, none).
species_parent(gengar, haunter).
species_parent(geodude, none).
species_parent(gible, none).
species_parent(gigalith, boldore).
species_parent(girafarig, none).
species_parent(giratina, none).
species_parent(glaceon, eevee).
species_parent(glalie, snorunt).
species_parent(glameow, none).
species_parent(gligar, none).
species_parent(gliscor, gligar).
species_parent(gloom, oddish).
species_parent(gogoat, skiddo).
species_parent(golbat, zubat).
species_parent(goldeen, none).
species_parent(golduck, psyduck).
species_parent(golem, graveler).
species_parent(golett, none).
species_parent(golurk, golett).
species_parent(goodra, sliggoo).
species_parent(goomy, none).
species_parent(gorebyss, clamperl).
species_parent(gothita, none).
species_parent(gothitelle, gothorita).
species_parent(gothorita, gothita).
species_parent(gourgeist, pumpkaboo).
species_parent(granbull, snubbull).
species_parent(graveler, geodude).
species_parent(greninja, frogadier).
species_parent(grimer, none).
species_parent(grotle, turtwig).
species_parent(groudon, none).
species_parent(grovyle, treecko).
species_parent(growlithe, none).
species_parent(grumpig, spoink).
species_parent(gulpin, none).
species_parent(gurdurr, timburr).
species_parent(gyarados, magikarp).
species_parent(happiny, none).
species_parent(hariyama, makuhita).
species_parent(haunter, gastly).
species_parent(hawlucha, none).
species_parent(haxorus, fraxure).
species_parent(heatmor, none).
species_parent(heatran, none).
species_parent(heliolisk, helioptile).
species_parent(helioptile, none).
species_parent(heracross, none).
species_parent(herdier, lillipup).
species_parent(hippopotas, none).
species_parent(hippowdon, hippopotas).
species_parent(hitmonchan, tyrogue).
species_parent(hitmonlee, tyrogue).
species_parent(hitmontop, tyrogue).
species_parent(ho_oh, none).
species_parent(honchkrow, murkrow).
species_parent(honedge, none).
species_parent(hoopa, none).
species_parent(hoothoot, none).
species_parent(hoppip, none).
species_parent(horsea, none).
species_parent(houndoom, houndour).
species_parent(houndour, none).
species_parent(huntail, clamperl).
species_parent(hydreigon, zweilous).
species_parent(hypno, drowzee).
species_parent(igglybuff, none).
species_parent(illumise, none).
species_parent(infernape, monferno).
species_parent(inkay, none).
species_parent(ivysaur, bulbasaur).
species_parent(jellicent, frillish).
species_parent(jigglypuff, igglybuff).
species_parent(jirachi, none).
species_parent(jolteon, eevee).
species_parent(joltik, none).
species_parent(jumpluff, skiploom).
species_parent(jynx, smoochum).
species_parent(kabuto, none).
species_parent(kabutops, kabuto).
species_parent(kadabra, abra).
species_parent(kakuna, weedle).
species_parent(kangaskhan, none).
species_parent(karrablast, none).
species_parent(kecleon, none).
species_parent(keldeo, none).
species_parent(kingdra, seadra).
species_parent(kingler, krabby).
species_parent(kirlia, ralts).
species_parent(klang, klink).
species_parent(klefki, none).
species_parent(klink, none).
species_parent(klinklang, klang).
species_parent(koffing, none).
species_parent(krabby, none).
species_parent(kricketot, none).
species_parent(kricketune, kricketot).
species_parent(krokorok, sandile).
species_parent(krookodile, krokorok).
species_parent(kyogre, none).
species_parent(kyurem, none).
species_parent(lairon, aron).
species_parent(lampent, litwick).
species_parent(landorus, none).
species_parent(lanturn, chinchou).
species_parent(lapras, none).
species_parent(larvesta, none).
species_parent(larvitar, none).
species_parent(latias, none).
species_parent(latios, none).
species_parent(leafeon, eevee).
species_parent(leavanny, swadloon).
species_parent(ledian, ledyba).
species_parent(ledyba, none).
species_parent(lickilicky, lickitung).
species_parent(lickitung, none).
species_parent(liepard, purrloin).
species_parent(lileep, none).
species_parent(lilligant, petilil).
species_parent(lillipup, none).
species_parent(linoone, zigzagoon).
species_parent(litleo, none).
species_parent(litwick, none).
species_parent(lombre, lotad).
species_parent(lopunny, buneary).
species_parent(lotad, none).
species_parent(loudred, whismur).
species_parent(lucario, riolu).
species_parent(ludicolo, lombre).
species_parent(lugia, none).
species_parent(lumineon, finneon).
species_parent(lunatone, none).
species_parent(luvdisc, none).
species_parent(luxio, shinx).
species_parent(luxray, luxio).
species_parent(machamp, machoke).
species_parent(machoke, machop).
species_parent(machop, none).
species_parent(magby, none).
species_parent(magcargo, slugma).
species_parent(magikarp, none).
species_parent(magmar, magby).
species_parent(magmortar, magmar).
species_parent(magnemite, none).
species_parent(magneton, magnemite).
species_parent(magnezone, magneton).
species_parent(makuhita, none).
species_parent(malamar, inkay).
species_parent(mamoswine, piloswine).
species_parent(manaphy, none).
species_parent(mandibuzz, vullaby).
species_parent(manectric, electrike).
species_parent(mankey, none).
species_parent(mantine, mantyke).
species_parent(mantyke, none).
species_parent(maractus, none).
species_parent(mareep, none).
species_parent(marill, azurill).
species_parent(marowak, cubone).
species_parent(marshtomp, mudkip).
species_parent(masquerain, surskit).
species_parent(mawile, none).
species_parent(medicham, meditite).
species_parent(meditite, none).
species_parent(meganium, bayleef).
species_parent(meloetta, none).
species_parent(meowstic, espurr).
species_parent(meowth, none).
species_parent(mesprit, none).
species_parent(metagross, metang).
species_parent(metang, beldum).
species_parent(metapod, caterpie).
species_parent(mew, none).
species_parent(mewtwo, none).
species_parent(mienfoo, none).
species_parent(mienshao, mienfoo).
species_parent(mightyena, poochyena).
species_parent(milotic, feebas).
species_parent(miltank, none).
species_parent(mime_jr, none).
species_parent(minccino, none).
species_parent(minun, none).
species_parent(misdreavus, none).
species_parent(mismagius, misdreavus).
species_parent(moltres, none).
species_parent(monferno, chimchar).
species_parent(mothim, burmy).
species_parent(mr_mime, mime_jr).
species_parent(mudkip, none).
species_parent(muk, grimer).
species_parent(munchlax, none).
species_parent(munna, none).
species_parent(murkrow, none).
species_parent(musharna, munna).
species_parent(natu, none).
species_parent(nidoking, nidorino).
species_parent(nidoqueen, nidorina).
species_parent(nidoran_f, none).
species_parent(nidoran_m, none).
species_parent(nidorina, nidoran_f).
species_parent(nidorino, nidoran_m).
species_parent(nincada, none).
species_parent(ninetales, vulpix).
species_parent(ninjask, nincada).
species_parent(noctowl, hoothoot).
species_parent(noibat, none).
species_parent(noivern, noibat).
species_parent(nosepass, none).
species_parent(numel, none).
species_parent(nuzleaf, seedot).
species_parent(octillery, remoraid).
species_parent(oddish, none).
species_parent(omanyte, none).
species_parent(omastar, omanyte).
species_parent(onix, none).
species_parent(oshawott, none).
species_parent(pachirisu, none).
species_parent(palkia, none).
species_parent(palpitoad, tympole).
species_parent(pancham, none).
species_parent(pangoro, pancham).
species_parent(panpour, none).
species_parent(pansage, none).
species_parent(pansear, none).
species_parent(paras, none).
species_parent(parasect, paras).
species_parent(patrat, none).
species_parent(pawniard, none).
species_parent(pelipper, wingull).
species_parent(persian, meowth).
species_parent(petilil, none).
species_parent(phanpy, none).
species_parent(phantump, none).
species_parent(phione, none).
species_parent(pichu, none).
species_parent(pidgeot, pidgeotto).
species_parent(pidgeotto, pidgey).
species_parent(pidgey, none).
species_parent(pidove, none).
species_parent(pignite, tepig).
species_parent(pikachu, pichu).
species_parent(piloswine, swinub).
species_parent(pineco, none).
species_parent(pinsir, none).
species_parent(piplup, none).
species_parent(plusle, none).
species_parent(politoed, poliwhirl).
species_parent(poliwag, none).
species_parent(poliwhirl, poliwag).
species_parent(poliwrath, poliwhirl).
species_parent(ponyta, none).
species_parent(poochyena, none).
species_parent(porygon, none).
species_parent(porygon_z, porygon2).
species_parent(porygon2, porygon).
species_parent(primeape, mankey).
species_parent(prinplup, piplup).
species_parent(probopass, nosepass).
species_parent(psyduck, none).
species_parent(pumpkaboo, none).
species_parent(pupitar, larvitar).
species_parent(purrloin, none).
species_parent(purugly, glameow).
species_parent(pyroar, litleo).
species_parent(quagsire, wooper).
species_parent(quilava, cyndaquil).
species_parent(quilladin, chespin).
species_parent(qwilfish, none).
species_parent(raichu, pikachu).
species_parent(raikou, none).
species_parent(ralts, none).
species_parent(rampardos, cranidos).
species_parent(rapidash, ponyta).
species_parent(raticate, rattata).
species_parent(rattata, none).
species_parent(rayquaza, none).
species_parent(regice, none).
species_parent(regigigas, none).
species_parent(regirock, none).
species_parent(registeel, none).
species_parent(relicanth, none).
species_parent(remoraid, none).
species_parent(reshiram, none).
species_parent(reuniclus, duosion).
species_parent(rhydon, rhyhorn).
species_parent(rhyhorn, none).
species_parent(rhyperior, rhydon).
species_parent(riolu, none).
species_parent(roggenrola, none).
species_parent(roselia, budew).
species_parent(roserade, roselia).
species_parent(rotom, none).
species_parent(rufflet, none).
species_parent(sableye, none).
species_parent(salamence, shelgon).
species_parent(samurott, dewott).
species_parent(sandile, none).
species_parent(sandshrew, none).
species_parent(sandslash, sandshrew).
species_parent(sawk, none).
species_parent(sawsbuck, deerling).
species_parent(scatterbug, none).
species_parent(sceptile, grovyle).
species_parent(scizor, scyther).
species_parent(scolipede, whirlipede).
species_parent(scrafty, scraggy).
species_parent(scraggy, none).
species_parent(scyther, none).
species_parent(seadra, horsea).
species_parent(seaking, goldeen).
species_parent(sealeo, spheal).
species_parent(seedot, none).
species_parent(seel, none).
species_parent(seismitoad, palpitoad).
species_parent(sentret, none).
species_parent(serperior, servine).
species_parent(servine, snivy).
species_parent(seviper, none).
species_parent(sewaddle, none).
species_parent(sharpedo, carvanha).
species_parent(shaymin, none).
species_parent(shedinja, nincada).
species_parent(shelgon, bagon).
species_parent(shellder, none).
species_parent(shellos, none).
species_parent(shelmet, none).
species_parent(shieldon, none).
species_parent(shiftry, nuzleaf).
species_parent(shinx, none).
species_parent(shroomish, none).
species_parent(shuckle, none).
species_parent(shuppet, none).
species_parent(sigilyph, none).
species_parent(silcoon, wurmple).
species_parent(simipour, panpour).
species_parent(simisage, pansage).
species_parent(simisear, pansear).
species_parent(skarmory, none).
species_parent(skiddo, none).
species_parent(skiploom, hoppip).
species_parent(skitty, none).
species_parent(skorupi, none).
species_parent(skrelp, none).
species_parent(skuntank, stunky).
species_parent(slaking, vigoroth).
species_parent(slakoth, none).
species_parent(sliggoo, goomy).
species_parent(slowbro, slowpoke).
species_parent(slowking, slowpoke).
species_parent(slowpoke, none).
species_parent(slugma, none).
species_parent(slurpuff, swirlix).
species_parent(smeargle, none).
species_parent(smoochum, none).
species_parent(sneasel, none).
species_parent(snivy, none).
species_parent(snorlax, munchlax).
species_parent(snorunt, none).
species_parent(snover, none).
species_parent(snubbull, none).
species_parent(solosis, none).
species_parent(solrock, none).
species_parent(spearow, none).
species_parent(spewpa, scatterbug).
species_parent(spheal, none).
species_parent(spinarak, none).
species_parent(spinda, none).
species_parent(spiritomb, none).
species_parent(spoink, none).
species_parent(spritzee, none).
species_parent(squirtle, none).
species_parent(stantler, none).
species_parent(staraptor, staravia).
species_parent(staravia, starly).
species_parent(starly, none).
species_parent(starmie, staryu).
species_parent(staryu, none).
species_parent(steelix, onix).
species_parent(stoutland, herdier).
species_parent(stunfisk, none).
species_parent(stunky, none).
species_parent(sudowoodo, bonsly).
species_parent(suicune, none).
species_parent(sunflora, sunkern).
species_parent(sunkern, none).
species_parent(surskit, none).
species_parent(swablu, none).
species_parent(swadloon, sewaddle).
species_parent(swalot, gulpin).
species_parent(swampert, marshtomp).
species_parent(swanna, ducklett).
species_parent(swellow, taillow).
species_parent(swinub, none).
species_parent(swirlix, none).
species_parent(swoobat, woobat).
species_parent(sylveon, eevee).
species_parent(taillow, none).
species_parent(talonflame, fletchinder).
species_parent(tangela, none).
species_parent(tangrowth, tangela).
species_parent(tauros, none).
species_parent(teddiursa, none).
species_parent(tentacool, none).
species_parent(tentacruel, tentacool).
species_parent(tepig, none).
species_parent(terrakion, none).
species_parent(throh, none).
species_parent(thundurus, none).
species_parent(timburr, none).
species_parent(tirtouga, none).
species_parent(togekiss, togetic).
species_parent(togepi, none).
species_parent(togetic, togepi).
species_parent(torchic, none).
species_parent(torkoal, none).
species_parent(tornadus, none).
species_parent(torterra, grotle).
species_parent(totodile, none).
species_parent(toxicroak, croagunk).
species_parent(tranquill, pidove).
species_parent(trapinch, none).
species_parent(treecko, none).
species_parent(trevenant, phantump).
species_parent(tropius, none).
species_parent(trubbish, none).
species_parent(turtwig, none).
species_parent(tympole, none).
species_parent(tynamo, none).
species_parent(typhlosion, quilava).
species_parent(tyranitar, pupitar).
species_parent(tyrantrum, tyrunt).
species_parent(tyrogue, none).
species_parent(tyrunt, none).
species_parent(umbreon, eevee).
species_parent(unfezant, tranquill).
species_parent(unown, none).
species_parent(ursaring, teddiursa).
species_parent(uxie, none).
species_parent(vanillish, vanillite).
species_parent(vanillite, none).
species_parent(vanilluxe, vanillish).
species_parent(vaporeon, eevee).
species_parent(venipede, none).
species_parent(venomoth, venonat).
species_parent(venonat, none).
species_parent(venusaur, ivysaur).
species_parent(vespiquen, combee).
species_parent(vibrava, trapinch).
species_parent(victini, none).
species_parent(victreebel, weepinbell).
species_parent(vigoroth, slakoth).
species_parent(vileplume, gloom).
species_parent(virizion, none).
species_parent(vivillon, spewpa).
species_parent(volbeat, none).
species_parent(volcanion, none).
species_parent(volcarona, larvesta).
species_parent(voltorb, none).
species_parent(vullaby, none).
species_parent(vulpix, none).
species_parent(wailmer, none).
species_parent(wailord, wailmer).
species_parent(walrein, sealeo).
species_parent(wartortle, squirtle).
species_parent(watchog, patrat).
species_parent(weavile, sneasel).
species_parent(weedle, none).
species_parent(weepinbell, bellsprout).
species_parent(weezing, koffing).
species_parent(whimsicott, cottonee).
species_parent(whirlipede, venipede).
species_parent(whiscash, barboach).
species_parent(whismur, none).
species_parent(wigglytuff, jigglypuff).
species_parent(wingull, none).
species_parent(wobbuffet, wynaut).
species_parent(woobat, none).
species_parent(wooper, none).
species_parent(wormadam, burmy).
species_parent(wurmple, none).
species_parent(wynaut, none).
species_parent(xatu, natu).
species_parent(xerneas, none).
species_parent(yamask, none).
species_parent(yanma, none).
species_parent(yanmega, yanma).
species_parent(yveltal, none).
species_parent(zangoose, none).
species_parent(zapdos, none).
species_parent(zebstrika, blitzle).
species_parent(zekrom, none).
species_parent(zigzagoon, none).
species_parent(zoroark, zorua).
species_parent(zorua, none).
species_parent(zubat, none).
species_parent(zweilous, deino).
species_parent(zygarde, none).

% genderless(species_name).
genderless(arceus).
genderless(articuno).
genderless(azelf).
genderless(baltoy).
genderless(beldum).
genderless(bronzong).
genderless(bronzor).
genderless(carbink).
genderless(celebi).
genderless(claydol).
genderless(cobalion).
genderless(cryogonal).
genderless(darkrai).
genderless(deoxys).
genderless(dialga).
genderless(diancie).
genderless(ditto).
genderless(electrode).
genderless(entei).
genderless(genesect).
genderless(giratina).
genderless(golett).
genderless(golurk).
genderless(groudon).
genderless(ho_oh).
genderless(hoopa).
genderless(jirachi).
genderless(keldeo).
genderless(klang).
genderless(klink).
genderless(klinklang).
genderless(kyogre).
genderless(kyurem).
genderless(lugia).
genderless(lunatone).
genderless(magnemite).
genderless(magneton).
genderless(magnezone).
genderless(manaphy).
genderless(meloetta).
genderless(mesprit).
genderless(metagross).
genderless(metang).
genderless(mew).
genderless(mewtwo).
genderless(moltres).
genderless(palkia).
genderless(phione).
genderless(porygon).
genderless(porygon_z).
genderless(porygon2).
genderless(raikou).
genderless(rayquaza).
genderless(regice).
genderless(regigigas).
genderless(regirock).
genderless(registeel).
genderless(reshiram).
genderless(rotom).
genderless(shaymin).
genderless(shedinja).
genderless(solrock).
genderless(starmie).
genderless(staryu).
genderless(suicune).
genderless(terrakion).
genderless(unown).
genderless(uxie).
genderless(victini).
genderless(virizion).
genderless(volcanion).
genderless(voltorb).
genderless(xerneas).
genderless(yveltal).
genderless(zapdos).
genderless(zekrom).
genderless(zygarde).

% species_egg_group(species_name, egg_group_name).
species_egg_group(abomasnow, monster).
species_egg_group(abomasnow, plant).
species_egg_group(abra, humanshape).
species_egg_group(absol, ground).
species_egg_group(accelgor, bug).
species_egg_group(aegislash, mineral).
species_egg_group(aerodactyl, flying).
species_egg_group(aggron, monster).
species_egg_group(aipom, ground).
species_egg_group(alakazam, humanshape).
species_egg_group(alomomola, water1).
species_egg_group(alomomola, water2).
species_egg_group(altaria, dragon).
species_egg_group(altaria, flying).
species_egg_group(amaura, monster).
species_egg_group(ambipom, ground).
species_egg_group(amoonguss, plant).
species_egg_group(ampharos, ground).
species_egg_group(ampharos, monster).
species_egg_group(anorith, water3).
species_egg_group(arbok, dragon).
species_egg_group(arbok, ground).
species_egg_group(arcanine, ground).
species_egg_group(arceus, no_eggs).
species_egg_group(archen, flying).
species_egg_group(archen, water3).
species_egg_group(archeops, flying).
species_egg_group(archeops, water3).
species_egg_group(ariados, bug).
species_egg_group(armaldo, water3).
species_egg_group(aromatisse, fairy).
species_egg_group(aron, monster).
species_egg_group(articuno, no_eggs).
species_egg_group(audino, fairy).
species_egg_group(aurorus, monster).
species_egg_group(avalugg, monster).
species_egg_group(axew, dragon).
species_egg_group(axew, monster).
species_egg_group(azelf, no_eggs).
species_egg_group(azumarill, fairy).
species_egg_group(azumarill, water1).
species_egg_group(azurill, no_eggs).
species_egg_group(bagon, dragon).
species_egg_group(baltoy, mineral).
species_egg_group(banette, indeterminate).
species_egg_group(barbaracle, water3).
species_egg_group(barboach, water2).
species_egg_group(basculin, water2).
species_egg_group(bastiodon, monster).
species_egg_group(bayleef, monster).
species_egg_group(bayleef, plant).
species_egg_group(beartic, ground).
species_egg_group(beautifly, bug).
species_egg_group(beedrill, bug).
species_egg_group(beheeyem, humanshape).
species_egg_group(beldum, mineral).
species_egg_group(bellossom, plant).
species_egg_group(bellsprout, plant).
species_egg_group(bergmite, monster).
species_egg_group(bibarel, ground).
species_egg_group(bibarel, water1).
species_egg_group(bidoof, ground).
species_egg_group(bidoof, water1).
species_egg_group(binacle, water3).
species_egg_group(bisharp, humanshape).
species_egg_group(blastoise, monster).
species_egg_group(blastoise, water1).
species_egg_group(blaziken, ground).
species_egg_group(blissey, fairy).
species_egg_group(blitzle, ground).
species_egg_group(boldore, mineral).
species_egg_group(bonsly, no_eggs).
species_egg_group(bouffalant, ground).
species_egg_group(braixen, ground).
species_egg_group(braviary, flying).
species_egg_group(breloom, fairy).
species_egg_group(breloom, plant).
species_egg_group(bronzong, mineral).
species_egg_group(bronzor, mineral).
species_egg_group(budew, no_eggs).
species_egg_group(buizel, ground).
species_egg_group(buizel, water1).
species_egg_group(bulbasaur, monster).
species_egg_group(bulbasaur, plant).
species_egg_group(buneary, ground).
species_egg_group(buneary, humanshape).
species_egg_group(bunnelby, ground).
species_egg_group(burmy, bug).
species_egg_group(butterfree, bug).
species_egg_group(cacnea, humanshape).
species_egg_group(cacnea, plant).
species_egg_group(cacturne, humanshape).
species_egg_group(cacturne, plant).
species_egg_group(camerupt, ground).
species_egg_group(carbink, fairy).
species_egg_group(carbink, mineral).
species_egg_group(carnivine, plant).
species_egg_group(carracosta, water1).
species_egg_group(carracosta, water3).
species_egg_group(carvanha, water2).
species_egg_group(cascoon, bug).
species_egg_group(castform, fairy).
species_egg_group(castform, indeterminate).
species_egg_group(caterpie, bug).
species_egg_group(celebi, no_eggs).
species_egg_group(chandelure, indeterminate).
species_egg_group(chansey, fairy).
species_egg_group(charizard, dragon).
species_egg_group(charizard, monster).
species_egg_group(charmander, dragon).
species_egg_group(charmander, monster).
species_egg_group(charmeleon, dragon).
species_egg_group(charmeleon, monster).
species_egg_group(chatot, flying).
species_egg_group(cherrim, fairy).
species_egg_group(cherrim, plant).
species_egg_group(cherubi, fairy).
species_egg_group(cherubi, plant).
species_egg_group(chesnaught, ground).
species_egg_group(chespin, ground).
species_egg_group(chikorita, monster).
species_egg_group(chikorita, plant).
species_egg_group(chimchar, ground).
species_egg_group(chimchar, humanshape).
species_egg_group(chimecho, indeterminate).
species_egg_group(chinchou, water2).
species_egg_group(chingling, no_eggs).
species_egg_group(cinccino, ground).
species_egg_group(clamperl, water1).
species_egg_group(clauncher, water1).
species_egg_group(clauncher, water3).
species_egg_group(clawitzer, water1).
species_egg_group(clawitzer, water3).
species_egg_group(claydol, mineral).
species_egg_group(clefable, fairy).
species_egg_group(clefairy, fairy).
species_egg_group(cleffa, no_eggs).
species_egg_group(cloyster, water3).
species_egg_group(cobalion, no_eggs).
species_egg_group(cofagrigus, indeterminate).
species_egg_group(cofagrigus, mineral).
species_egg_group(combee, bug).
species_egg_group(combusken, ground).
species_egg_group(conkeldurr, humanshape).
species_egg_group(corphish, water1).
species_egg_group(corphish, water3).
species_egg_group(corsola, water1).
species_egg_group(corsola, water3).
species_egg_group(cottonee, fairy).
species_egg_group(cottonee, plant).
species_egg_group(cradily, water3).
species_egg_group(cranidos, monster).
species_egg_group(crawdaunt, water1).
species_egg_group(crawdaunt, water3).
species_egg_group(cresselia, no_eggs).
species_egg_group(croagunk, humanshape).
species_egg_group(crobat, flying).
species_egg_group(croconaw, monster).
species_egg_group(croconaw, water1).
species_egg_group(crustle, bug).
species_egg_group(crustle, mineral).
species_egg_group(cryogonal, mineral).
species_egg_group(cubchoo, ground).
species_egg_group(cubone, monster).
species_egg_group(cyndaquil, ground).
species_egg_group(darkrai, no_eggs).
species_egg_group(darmanitan, ground).
species_egg_group(darumaka, ground).
species_egg_group(dedenne, fairy).
species_egg_group(dedenne, ground).
species_egg_group(deerling, ground).
species_egg_group(deino, dragon).
species_egg_group(delcatty, fairy).
species_egg_group(delcatty, ground).
species_egg_group(delibird, ground).
species_egg_group(delibird, water1).
species_egg_group(delphox, ground).
species_egg_group(deoxys, no_eggs).
species_egg_group(dewgong, ground).
species_egg_group(dewgong, water1).
species_egg_group(dewott, ground).
species_egg_group(dialga, no_eggs).
species_egg_group(diancie, no_eggs).
species_egg_group(diggersby, ground).
species_egg_group(diglett, ground).
species_egg_group(ditto, ditto).
species_egg_group(dodrio, flying).
species_egg_group(doduo, flying).
species_egg_group(donphan, ground).
species_egg_group(doublade, mineral).
species_egg_group(dragalge, dragon).
species_egg_group(dragalge, water1).
species_egg_group(dragonair, dragon).
species_egg_group(dragonair, water1).
species_egg_group(dragonite, dragon).
species_egg_group(dragonite, water1).
species_egg_group(drapion, bug).
species_egg_group(drapion, water3).
species_egg_group(dratini, dragon).
species_egg_group(dratini, water1).
species_egg_group(drifblim, indeterminate).
species_egg_group(drifloon, indeterminate).
species_egg_group(drilbur, ground).
species_egg_group(drowzee, humanshape).
species_egg_group(druddigon, dragon).
species_egg_group(druddigon, monster).
species_egg_group(ducklett, flying).
species_egg_group(ducklett, water1).
species_egg_group(dugtrio, ground).
species_egg_group(dunsparce, ground).
species_egg_group(duosion, indeterminate).
species_egg_group(durant, bug).
species_egg_group(dusclops, indeterminate).
species_egg_group(dusknoir, indeterminate).
species_egg_group(duskull, indeterminate).
species_egg_group(dustox, bug).
species_egg_group(dwebble, bug).
species_egg_group(dwebble, mineral).
species_egg_group(eelektrik, indeterminate).
species_egg_group(eelektross, indeterminate).
species_egg_group(eevee, ground).
species_egg_group(ekans, dragon).
species_egg_group(ekans, ground).
species_egg_group(electabuzz, humanshape).
species_egg_group(electivire, humanshape).
species_egg_group(electrike, ground).
species_egg_group(electrode, mineral).
species_egg_group(elekid, no_eggs).
species_egg_group(elgyem, humanshape).
species_egg_group(emboar, ground).
species_egg_group(emolga, ground).
species_egg_group(empoleon, ground).
species_egg_group(empoleon, water1).
species_egg_group(entei, no_eggs).
species_egg_group(escavalier, bug).
species_egg_group(espeon, ground).
species_egg_group(espurr, ground).
species_egg_group(excadrill, ground).
species_egg_group(exeggcute, plant).
species_egg_group(exeggutor, plant).
species_egg_group(exploud, ground).
species_egg_group(exploud, monster).
species_egg_group(farfetchd, flying).
species_egg_group(farfetchd, ground).
species_egg_group(fearow, flying).
species_egg_group(feebas, dragon).
species_egg_group(feebas, water1).
species_egg_group(fennekin, ground).
species_egg_group(feraligatr, monster).
species_egg_group(feraligatr, water1).
species_egg_group(ferroseed, mineral).
species_egg_group(ferroseed, plant).
species_egg_group(ferrothorn, mineral).
species_egg_group(ferrothorn, plant).
species_egg_group(finneon, water2).
species_egg_group(flaaffy, ground).
species_egg_group(flaaffy, monster).
species_egg_group(flabebe, fairy).
species_egg_group(flareon, ground).
species_egg_group(fletchinder, flying).
species_egg_group(fletchling, flying).
species_egg_group(floatzel, ground).
species_egg_group(floatzel, water1).
species_egg_group(floette, fairy).
species_egg_group(florges, fairy).
species_egg_group(flygon, bug).
species_egg_group(foongus, plant).
species_egg_group(forretress, bug).
species_egg_group(fraxure, dragon).
species_egg_group(fraxure, monster).
species_egg_group(frillish, indeterminate).
species_egg_group(froakie, water1).
species_egg_group(frogadier, water1).
species_egg_group(froslass, fairy).
species_egg_group(froslass, mineral).
species_egg_group(furfrou, ground).
species_egg_group(furret, ground).
species_egg_group(gabite, dragon).
species_egg_group(gabite, monster).
species_egg_group(gallade, indeterminate).
species_egg_group(galvantula, bug).
species_egg_group(garbodor, mineral).
species_egg_group(garchomp, dragon).
species_egg_group(garchomp, monster).
species_egg_group(gardevoir, indeterminate).
species_egg_group(gastly, indeterminate).
species_egg_group(gastrodon, indeterminate).
species_egg_group(gastrodon, water1).
species_egg_group(genesect, no_eggs).
species_egg_group(gengar, indeterminate).
species_egg_group(geodude, mineral).
species_egg_group(gible, dragon).
species_egg_group(gible, monster).
species_egg_group(gigalith, mineral).
species_egg_group(girafarig, ground).
species_egg_group(giratina, no_eggs).
species_egg_group(glaceon, ground).
species_egg_group(glalie, fairy).
species_egg_group(glalie, mineral).
species_egg_group(glameow, ground).
species_egg_group(gligar, bug).
species_egg_group(gliscor, bug).
species_egg_group(gloom, plant).
species_egg_group(gogoat, ground).
species_egg_group(golbat, flying).
species_egg_group(goldeen, water2).
species_egg_group(golduck, ground).
species_egg_group(golduck, water1).
species_egg_group(golem, mineral).
species_egg_group(golett, mineral).
species_egg_group(golurk, mineral).
species_egg_group(goodra, dragon).
species_egg_group(goomy, dragon).
species_egg_group(gorebyss, water1).
species_egg_group(gothita, humanshape).
species_egg_group(gothitelle, humanshape).
species_egg_group(gothorita, humanshape).
species_egg_group(gourgeist, indeterminate).
species_egg_group(granbull, fairy).
species_egg_group(granbull, ground).
species_egg_group(graveler, mineral).
species_egg_group(greninja, water1).
species_egg_group(grimer, indeterminate).
species_egg_group(grotle, monster).
species_egg_group(grotle, plant).
species_egg_group(groudon, no_eggs).
species_egg_group(grovyle, dragon).
species_egg_group(grovyle, monster).
species_egg_group(growlithe, ground).
species_egg_group(grumpig, ground).
species_egg_group(gulpin, indeterminate).
species_egg_group(gurdurr, humanshape).
species_egg_group(gyarados, dragon).
species_egg_group(gyarados, water2).
species_egg_group(happiny, no_eggs).
species_egg_group(hariyama, humanshape).
species_egg_group(haunter, indeterminate).
species_egg_group(hawlucha, humanshape).
species_egg_group(haxorus, dragon).
species_egg_group(haxorus, monster).
species_egg_group(heatmor, ground).
species_egg_group(heatran, no_eggs).
species_egg_group(heliolisk, dragon).
species_egg_group(heliolisk, monster).
species_egg_group(helioptile, dragon).
species_egg_group(helioptile, monster).
species_egg_group(heracross, bug).
species_egg_group(herdier, ground).
species_egg_group(hippopotas, ground).
species_egg_group(hippowdon, ground).
species_egg_group(hitmonchan, humanshape).
species_egg_group(hitmonlee, humanshape).
species_egg_group(hitmontop, humanshape).
species_egg_group(ho_oh, no_eggs).
species_egg_group(honchkrow, flying).
species_egg_group(honedge, mineral).
species_egg_group(hoopa, no_eggs).
species_egg_group(hoothoot, flying).
species_egg_group(hoppip, fairy).
species_egg_group(hoppip, plant).
species_egg_group(horsea, dragon).
species_egg_group(horsea, water1).
species_egg_group(houndoom, ground).
species_egg_group(houndour, ground).
species_egg_group(huntail, water1).
species_egg_group(hydreigon, dragon).
species_egg_group(hypno, humanshape).
species_egg_group(igglybuff, no_eggs).
species_egg_group(illumise, bug).
species_egg_group(illumise, humanshape).
species_egg_group(infernape, ground).
species_egg_group(infernape, humanshape).
species_egg_group(inkay, water1).
species_egg_group(inkay, water2).
species_egg_group(ivysaur, monster).
species_egg_group(ivysaur, plant).
species_egg_group(jellicent, indeterminate).
species_egg_group(jigglypuff, fairy).
species_egg_group(jirachi, no_eggs).
species_egg_group(jolteon, ground).
species_egg_group(joltik, bug).
species_egg_group(jumpluff, fairy).
species_egg_group(jumpluff, plant).
species_egg_group(jynx, humanshape).
species_egg_group(kabuto, water1).
species_egg_group(kabuto, water3).
species_egg_group(kabutops, water1).
species_egg_group(kabutops, water3).
species_egg_group(kadabra, humanshape).
species_egg_group(kakuna, bug).
species_egg_group(kangaskhan, monster).
species_egg_group(karrablast, bug).
species_egg_group(kecleon, ground).
species_egg_group(keldeo, no_eggs).
species_egg_group(kingdra, dragon).
species_egg_group(kingdra, water1).
species_egg_group(kingler, water3).
species_egg_group(kirlia, indeterminate).
species_egg_group(klang, mineral).
species_egg_group(klefki, mineral).
species_egg_group(klink, mineral).
species_egg_group(klinklang, mineral).
species_egg_group(koffing, indeterminate).
species_egg_group(krabby, water3).
species_egg_group(kricketot, bug).
species_egg_group(kricketune, bug).
species_egg_group(krokorok, ground).
species_egg_group(krookodile, ground).
species_egg_group(kyogre, no_eggs).
species_egg_group(kyurem, no_eggs).
species_egg_group(lairon, monster).
species_egg_group(lampent, indeterminate).
species_egg_group(landorus, no_eggs).
species_egg_group(lanturn, water2).
species_egg_group(lapras, monster).
species_egg_group(lapras, water1).
species_egg_group(larvesta, bug).
species_egg_group(larvitar, monster).
species_egg_group(latias, no_eggs).
species_egg_group(latios, no_eggs).
species_egg_group(leafeon, ground).
species_egg_group(leavanny, bug).
species_egg_group(ledian, bug).
species_egg_group(ledyba, bug).
species_egg_group(lickilicky, monster).
species_egg_group(lickitung, monster).
species_egg_group(liepard, ground).
species_egg_group(lileep, water3).
species_egg_group(lilligant, plant).
species_egg_group(lillipup, ground).
species_egg_group(linoone, ground).
species_egg_group(litleo, ground).
species_egg_group(litwick, indeterminate).
species_egg_group(lombre, plant).
species_egg_group(lombre, water1).
species_egg_group(lopunny, ground).
species_egg_group(lopunny, humanshape).
species_egg_group(lotad, plant).
species_egg_group(lotad, water1).
species_egg_group(loudred, ground).
species_egg_group(loudred, monster).
species_egg_group(lucario, ground).
species_egg_group(lucario, humanshape).
species_egg_group(ludicolo, plant).
species_egg_group(ludicolo, water1).
species_egg_group(lugia, no_eggs).
species_egg_group(lumineon, water2).
species_egg_group(lunatone, mineral).
species_egg_group(luvdisc, water2).
species_egg_group(luxio, ground).
species_egg_group(luxray, ground).
species_egg_group(machamp, humanshape).
species_egg_group(machoke, humanshape).
species_egg_group(machop, humanshape).
species_egg_group(magby, no_eggs).
species_egg_group(magcargo, indeterminate).
species_egg_group(magikarp, dragon).
species_egg_group(magikarp, water2).
species_egg_group(magmar, humanshape).
species_egg_group(magmortar, humanshape).
species_egg_group(magnemite, mineral).
species_egg_group(magneton, mineral).
species_egg_group(magnezone, mineral).
species_egg_group(makuhita, humanshape).
species_egg_group(malamar, water1).
species_egg_group(malamar, water2).
species_egg_group(mamoswine, ground).
species_egg_group(manaphy, fairy).
species_egg_group(manaphy, water1).
species_egg_group(mandibuzz, flying).
species_egg_group(manectric, ground).
species_egg_group(mankey, ground).
species_egg_group(mantine, water1).
species_egg_group(mantyke, no_eggs).
species_egg_group(maractus, plant).
species_egg_group(mareep, ground).
species_egg_group(mareep, monster).
species_egg_group(marill, fairy).
species_egg_group(marill, water1).
species_egg_group(marowak, monster).
species_egg_group(marshtomp, monster).
species_egg_group(marshtomp, water1).
species_egg_group(masquerain, bug).
species_egg_group(masquerain, water1).
species_egg_group(mawile, fairy).
species_egg_group(mawile, ground).
species_egg_group(medicham, humanshape).
species_egg_group(meditite, humanshape).
species_egg_group(meganium, monster).
species_egg_group(meganium, plant).
species_egg_group(meloetta, no_eggs).
species_egg_group(meowstic, ground).
species_egg_group(meowth, ground).
species_egg_group(mesprit, no_eggs).
species_egg_group(metagross, mineral).
species_egg_group(metang, mineral).
species_egg_group(metapod, bug).
species_egg_group(mew, no_eggs).
species_egg_group(mewtwo, no_eggs).
species_egg_group(mienfoo, ground).
species_egg_group(mienfoo, humanshape).
species_egg_group(mienshao, ground).
species_egg_group(mienshao, humanshape).
species_egg_group(mightyena, ground).
species_egg_group(milotic, dragon).
species_egg_group(milotic, water1).
species_egg_group(miltank, ground).
species_egg_group(mime_jr, no_eggs).
species_egg_group(minccino, ground).
species_egg_group(minun, fairy).
species_egg_group(misdreavus, indeterminate).
species_egg_group(mismagius, indeterminate).
species_egg_group(moltres, no_eggs).
species_egg_group(monferno, ground).
species_egg_group(monferno, humanshape).
species_egg_group(mothim, bug).
species_egg_group(mr_mime, humanshape).
species_egg_group(mudkip, monster).
species_egg_group(mudkip, water1).
species_egg_group(muk, indeterminate).
species_egg_group(munchlax, no_eggs).
species_egg_group(munna, ground).
species_egg_group(murkrow, flying).
species_egg_group(musharna, ground).
species_egg_group(natu, flying).
species_egg_group(nidoking, ground).
species_egg_group(nidoking, monster).
species_egg_group(nidoqueen, no_eggs).
species_egg_group(nidoran_f, ground).
species_egg_group(nidoran_f, monster).
species_egg_group(nidoran_m, ground).
species_egg_group(nidoran_m, monster).
species_egg_group(nidorina, no_eggs).
species_egg_group(nidorino, ground).
species_egg_group(nidorino, monster).
species_egg_group(nincada, bug).
species_egg_group(ninetales, ground).
species_egg_group(ninjask, bug).
species_egg_group(noctowl, flying).
species_egg_group(noibat, flying).
species_egg_group(noivern, flying).
species_egg_group(nosepass, mineral).
species_egg_group(numel, ground).
species_egg_group(nuzleaf, ground).
species_egg_group(nuzleaf, plant).
species_egg_group(octillery, water1).
species_egg_group(octillery, water2).
species_egg_group(oddish, plant).
species_egg_group(omanyte, water1).
species_egg_group(omanyte, water3).
species_egg_group(omastar, water1).
species_egg_group(omastar, water3).
species_egg_group(onix, mineral).
species_egg_group(oshawott, ground).
species_egg_group(pachirisu, fairy).
species_egg_group(pachirisu, ground).
species_egg_group(palkia, no_eggs).
species_egg_group(palpitoad, water1).
species_egg_group(pancham, ground).
species_egg_group(pancham, humanshape).
species_egg_group(pangoro, ground).
species_egg_group(pangoro, humanshape).
species_egg_group(panpour, ground).
species_egg_group(pansage, ground).
species_egg_group(pansear, ground).
species_egg_group(paras, bug).
species_egg_group(paras, plant).
species_egg_group(parasect, bug).
species_egg_group(parasect, plant).
species_egg_group(patrat, ground).
species_egg_group(pawniard, humanshape).
species_egg_group(pelipper, flying).
species_egg_group(pelipper, water1).
species_egg_group(persian, ground).
species_egg_group(petilil, plant).
species_egg_group(phanpy, ground).
species_egg_group(phantump, indeterminate).
species_egg_group(phantump, plant).
species_egg_group(phione, fairy).
species_egg_group(phione, water1).
species_egg_group(pichu, no_eggs).
species_egg_group(pidgeot, flying).
species_egg_group(pidgeotto, flying).
species_egg_group(pidgey, flying).
species_egg_group(pidove, flying).
species_egg_group(pignite, ground).
species_egg_group(pikachu, fairy).
species_egg_group(pikachu, ground).
species_egg_group(piloswine, ground).
species_egg_group(pineco, bug).
species_egg_group(pinsir, bug).
species_egg_group(piplup, ground).
species_egg_group(piplup, water1).
species_egg_group(plusle, fairy).
species_egg_group(politoed, water1).
species_egg_group(poliwag, water1).
species_egg_group(poliwhirl, water1).
species_egg_group(poliwrath, water1).
species_egg_group(ponyta, ground).
species_egg_group(poochyena, ground).
species_egg_group(porygon, mineral).
species_egg_group(porygon_z, mineral).
species_egg_group(porygon2, mineral).
species_egg_group(primeape, ground).
species_egg_group(prinplup, ground).
species_egg_group(prinplup, water1).
species_egg_group(probopass, mineral).
species_egg_group(psyduck, ground).
species_egg_group(psyduck, water1).
species_egg_group(pumpkaboo, indeterminate).
species_egg_group(pupitar, monster).
species_egg_group(purrloin, ground).
species_egg_group(purugly, ground).
species_egg_group(pyroar, ground).
species_egg_group(quagsire, ground).
species_egg_group(quagsire, water1).
species_egg_group(quilava, ground).
species_egg_group(quilladin, ground).
species_egg_group(qwilfish, water2).
species_egg_group(raichu, fairy).
species_egg_group(raichu, ground).
species_egg_group(raikou, no_eggs).
species_egg_group(ralts, indeterminate).
species_egg_group(rampardos, monster).
species_egg_group(rapidash, ground).
species_egg_group(raticate, ground).
species_egg_group(rattata, ground).
species_egg_group(rayquaza, no_eggs).
species_egg_group(regice, no_eggs).
species_egg_group(regigigas, no_eggs).
species_egg_group(regirock, no_eggs).
species_egg_group(registeel, no_eggs).
species_egg_group(relicanth, water1).
species_egg_group(relicanth, water2).
species_egg_group(remoraid, water1).
species_egg_group(remoraid, water2).
species_egg_group(reshiram, no_eggs).
species_egg_group(reuniclus, indeterminate).
species_egg_group(rhydon, ground).
species_egg_group(rhydon, monster).
species_egg_group(rhyhorn, ground).
species_egg_group(rhyhorn, monster).
species_egg_group(rhyperior, ground).
species_egg_group(rhyperior, monster).
species_egg_group(riolu, no_eggs).
species_egg_group(roggenrola, mineral).
species_egg_group(roselia, fairy).
species_egg_group(roselia, plant).
species_egg_group(roserade, fairy).
species_egg_group(roserade, plant).
species_egg_group(rotom, indeterminate).
species_egg_group(rufflet, flying).
species_egg_group(sableye, humanshape).
species_egg_group(salamence, dragon).
species_egg_group(samurott, ground).
species_egg_group(sandile, ground).
species_egg_group(sandshrew, ground).
species_egg_group(sandslash, ground).
species_egg_group(sawk, humanshape).
species_egg_group(sawsbuck, ground).
species_egg_group(scatterbug, bug).
species_egg_group(sceptile, dragon).
species_egg_group(sceptile, monster).
species_egg_group(scizor, bug).
species_egg_group(scolipede, bug).
species_egg_group(scrafty, dragon).
species_egg_group(scrafty, ground).
species_egg_group(scraggy, dragon).
species_egg_group(scraggy, ground).
species_egg_group(scyther, bug).
species_egg_group(seadra, dragon).
species_egg_group(seadra, water1).
species_egg_group(seaking, water2).
species_egg_group(sealeo, ground).
species_egg_group(sealeo, water1).
species_egg_group(seedot, ground).
species_egg_group(seedot, plant).
species_egg_group(seel, ground).
species_egg_group(seel, water1).
species_egg_group(seismitoad, water1).
species_egg_group(sentret, ground).
species_egg_group(serperior, ground).
species_egg_group(serperior, plant).
species_egg_group(servine, ground).
species_egg_group(servine, plant).
species_egg_group(seviper, dragon).
species_egg_group(seviper, ground).
species_egg_group(sewaddle, bug).
species_egg_group(sharpedo, water2).
species_egg_group(shaymin, no_eggs).
species_egg_group(shedinja, mineral).
species_egg_group(shelgon, dragon).
species_egg_group(shellder, water3).
species_egg_group(shellos, indeterminate).
species_egg_group(shellos, water1).
species_egg_group(shelmet, bug).
species_egg_group(shieldon, monster).
species_egg_group(shiftry, ground).
species_egg_group(shiftry, plant).
species_egg_group(shinx, ground).
species_egg_group(shroomish, fairy).
species_egg_group(shroomish, plant).
species_egg_group(shuckle, bug).
species_egg_group(shuppet, indeterminate).
species_egg_group(sigilyph, flying).
species_egg_group(silcoon, bug).
species_egg_group(simipour, ground).
species_egg_group(simisage, ground).
species_egg_group(simisear, ground).
species_egg_group(skarmory, flying).
species_egg_group(skiddo, ground).
species_egg_group(skiploom, fairy).
species_egg_group(skiploom, plant).
species_egg_group(skitty, fairy).
species_egg_group(skitty, ground).
species_egg_group(skorupi, bug).
species_egg_group(skorupi, water3).
species_egg_group(skrelp, dragon).
species_egg_group(skrelp, water1).
species_egg_group(skuntank, ground).
species_egg_group(slaking, ground).
species_egg_group(slakoth, ground).
species_egg_group(sliggoo, dragon).
species_egg_group(slowbro, monster).
species_egg_group(slowbro, water1).
species_egg_group(slowking, monster).
species_egg_group(slowking, water1).
species_egg_group(slowpoke, monster).
species_egg_group(slowpoke, water1).
species_egg_group(slugma, indeterminate).
species_egg_group(slurpuff, fairy).
species_egg_group(smeargle, ground).
species_egg_group(smoochum, no_eggs).
species_egg_group(sneasel, ground).
species_egg_group(snivy, ground).
species_egg_group(snivy, plant).
species_egg_group(snorlax, monster).
species_egg_group(snorunt, fairy).
species_egg_group(snorunt, mineral).
species_egg_group(snover, monster).
species_egg_group(snover, plant).
species_egg_group(snubbull, fairy).
species_egg_group(snubbull, ground).
species_egg_group(solosis, indeterminate).
species_egg_group(solrock, mineral).
species_egg_group(spearow, flying).
species_egg_group(spewpa, bug).
species_egg_group(spheal, ground).
species_egg_group(spheal, water1).
species_egg_group(spinarak, bug).
species_egg_group(spinda, ground).
species_egg_group(spinda, humanshape).
species_egg_group(spiritomb, indeterminate).
species_egg_group(spoink, ground).
species_egg_group(spritzee, fairy).
species_egg_group(squirtle, monster).
species_egg_group(squirtle, water1).
species_egg_group(stantler, ground).
species_egg_group(staraptor, flying).
species_egg_group(staravia, flying).
species_egg_group(starly, flying).
species_egg_group(starmie, water3).
species_egg_group(staryu, water3).
species_egg_group(steelix, mineral).
species_egg_group(stoutland, ground).
species_egg_group(stunfisk, indeterminate).
species_egg_group(stunfisk, water1).
species_egg_group(stunky, ground).
species_egg_group(sudowoodo, mineral).
species_egg_group(suicune, no_eggs).
species_egg_group(sunflora, plant).
species_egg_group(sunkern, plant).
species_egg_group(surskit, bug).
species_egg_group(surskit, water1).
species_egg_group(swablu, dragon).
species_egg_group(swablu, flying).
species_egg_group(swadloon, bug).
species_egg_group(swalot, indeterminate).
species_egg_group(swampert, monster).
species_egg_group(swampert, water1).
species_egg_group(swanna, flying).
species_egg_group(swanna, water1).
species_egg_group(swellow, flying).
species_egg_group(swinub, ground).
species_egg_group(swirlix, fairy).
species_egg_group(swoobat, flying).
species_egg_group(swoobat, ground).
species_egg_group(sylveon, ground).
species_egg_group(taillow, flying).
species_egg_group(talonflame, flying).
species_egg_group(tangela, plant).
species_egg_group(tangrowth, plant).
species_egg_group(tauros, ground).
species_egg_group(teddiursa, ground).
species_egg_group(tentacool, water3).
species_egg_group(tentacruel, water3).
species_egg_group(tepig, ground).
species_egg_group(terrakion, no_eggs).
species_egg_group(throh, humanshape).
species_egg_group(thundurus, no_eggs).
species_egg_group(timburr, humanshape).
species_egg_group(tirtouga, water1).
species_egg_group(tirtouga, water3).
species_egg_group(togekiss, fairy).
species_egg_group(togekiss, flying).
species_egg_group(togepi, no_eggs).
species_egg_group(togetic, fairy).
species_egg_group(togetic, flying).
species_egg_group(torchic, ground).
species_egg_group(torkoal, ground).
species_egg_group(tornadus, no_eggs).
species_egg_group(torterra, monster).
species_egg_group(torterra, plant).
species_egg_group(totodile, monster).
species_egg_group(totodile, water1).
species_egg_group(toxicroak, humanshape).
species_egg_group(tranquill, flying).
species_egg_group(trapinch, bug).
species_egg_group(treecko, dragon).
species_egg_group(treecko, monster).
species_egg_group(trevenant, indeterminate).
species_egg_group(trevenant, plant).
species_egg_group(tropius, monster).
species_egg_group(tropius, plant).
species_egg_group(trubbish, mineral).
species_egg_group(turtwig, monster).
species_egg_group(turtwig, plant).
species_egg_group(tympole, water1).
species_egg_group(tynamo, indeterminate).
species_egg_group(typhlosion, ground).
species_egg_group(tyranitar, monster).
species_egg_group(tyrantrum, dragon).
species_egg_group(tyrantrum, monster).
species_egg_group(tyrogue, no_eggs).
species_egg_group(tyrunt, dragon).
species_egg_group(tyrunt, monster).
species_egg_group(umbreon, ground).
species_egg_group(unfezant, flying).
species_egg_group(unown, no_eggs).
species_egg_group(ursaring, ground).
species_egg_group(uxie, no_eggs).
species_egg_group(vanillish, mineral).
species_egg_group(vanillite, mineral).
species_egg_group(vanilluxe, mineral).
species_egg_group(vaporeon, ground).
species_egg_group(venipede, bug).
species_egg_group(venomoth, bug).
species_egg_group(venonat, bug).
species_egg_group(venusaur, monster).
species_egg_group(venusaur, plant).
species_egg_group(vespiquen, bug).
species_egg_group(vibrava, bug).
species_egg_group(victini, no_eggs).
species_egg_group(victreebel, plant).
species_egg_group(vigoroth, ground).
species_egg_group(vileplume, plant).
species_egg_group(virizion, no_eggs).
species_egg_group(vivillon, bug).
species_egg_group(volbeat, bug).
species_egg_group(volbeat, humanshape).
species_egg_group(volcanion, no_eggs).
species_egg_group(volcarona, bug).
species_egg_group(voltorb, mineral).
species_egg_group(vullaby, flying).
species_egg_group(vulpix, ground).
species_egg_group(wailmer, ground).
species_egg_group(wailmer, water2).
species_egg_group(wailord, ground).
species_egg_group(wailord, water2).
species_egg_group(walrein, ground).
species_egg_group(walrein, water1).
species_egg_group(wartortle, monster).
species_egg_group(wartortle, water1).
species_egg_group(watchog, ground).
species_egg_group(weavile, ground).
species_egg_group(weedle, bug).
species_egg_group(weepinbell, plant).
species_egg_group(weezing, indeterminate).
species_egg_group(whimsicott, fairy).
species_egg_group(whimsicott, plant).
species_egg_group(whirlipede, bug).
species_egg_group(whiscash, water2).
species_egg_group(whismur, ground).
species_egg_group(whismur, monster).
species_egg_group(wigglytuff, fairy).
species_egg_group(wingull, flying).
species_egg_group(wingull, water1).
species_egg_group(wobbuffet, indeterminate).
species_egg_group(woobat, flying).
species_egg_group(woobat, ground).
species_egg_group(wooper, ground).
species_egg_group(wooper, water1).
species_egg_group(wormadam, bug).
species_egg_group(wurmple, bug).
species_egg_group(wynaut, no_eggs).
species_egg_group(xatu, flying).
species_egg_group(xerneas, no_eggs).
species_egg_group(yamask, indeterminate).
species_egg_group(yamask, mineral).
species_egg_group(yanma, bug).
species_egg_group(yanmega, bug).
species_egg_group(yveltal, no_eggs).
species_egg_group(zangoose, ground).
species_egg_group(zapdos, no_eggs).
species_egg_group(zebstrika, ground).
species_egg_group(zekrom, no_eggs).
species_egg_group(zigzagoon, ground).
species_egg_group(zoroark, ground).
species_egg_group(zorua, ground).
species_egg_group(zubat, flying).
species_egg_group(zweilous, dragon).
species_egg_group(zygarde, no_eggs).

species_base_evolution(Species, Species) :-
    species_parent(Species, none).
species_base_evolution(Species, BaseSpecies) :-
    species_parent(Species, ParentSpecies),
    species_base_evolution(ParentSpecies, BaseSpecies).

adult_evolution(Species) :-
    species_base_evolution(Species, Base),
    Species \= Base.

% Ditto special case:
% "The female is the one who decides the species of the egg, except if using a
% ditto in which case it's always the pokemon that is not ditto (ditto can't be
% bred)."
% https://www.reddit.com/r/pokemon/comments/1p4pps/gen_vi_breeding_guide/
%
% note, ditto cannot breed with another ditto
%
% note, can_breed requires both parents are not babies

can_breed(ditto, FemaleSpecies) :-
    adult_evolution(FemaleSpecies),
    ditto \= FemaleSpecies.
can_breed(MaleSpecies, ditto) :-
    adult_evolution(MaleSpecies),
    ditto \= MaleSpecies.
can_breed(MaleSpecies, FemaleSpecies) :-
    % both must be adults
    adult_evolution(MaleSpecies),
    adult_evolution(FemaleSpecies),
    % cannot be genderless species
    \+genderless(MaleSpecies),
    \+genderless(FemaleSpecies),
    % must match male/female egg group
    species_egg_group(FemaleSpecies, EggGroup),
    species_egg_group(MaleSpecies, EggGroup),
    % that egg group cannot be no_eggs
    EggGroup \= no_eggs.

% child pokemon is base evolution of mother (special case for ditto)
child_pok(ditto, Female, ChildPok) :-
    can_breed(ditto, Female),
    species_base_evolution(Female, ChildPok).
child_pok(Male, ditto, ChildPok) :-
    can_breed(Male, ditto),
    species_base_evolution(Male, ChildPok).
child_pok(Male, Female, ChildPok) :-
    can_breed(Male, Female),
    Male \= ditto,
    Female \= ditto,
    species_base_evolution(Female, ChildPok).


